const DEFAULT_CORNER_RADIUS = 20;
const DEFAULT_CORNER_SMOOTHING = 0.6;
const DEFAULT_BACKGROUND_COLOR = "transparent";
const DEFAULT_BORDER_COLOR = "transparent";
const DEFAULT_BORDER_WIDTH = 0;
const BEZIER_KAPPA = 0.5519150244935105;

const SQUIRCLE_KAPPA = 0.9091;

export {
  DEFAULT_CORNER_RADIUS,
  DEFAULT_CORNER_SMOOTHING,
  DEFAULT_BACKGROUND_COLOR,
  DEFAULT_BORDER_COLOR,
  DEFAULT_BORDER_WIDTH,
  BEZIER_KAPPA,
  SQUIRCLE_KAPPA,
};
